### ISSUE TITLE
publishing to npm

### ISSUE THREAD

**Issue by mhuebert** [lezer-parser/clojure#10]
@marijnh we were wondering if you have any thoughts on how to handle publishing `lezer-clojure` to npm? During development I've been publishing a package scoped to my username (`@mhuebert/lezer-clojure`).

**Comment by marijnh** [comment]
Feel free to publish this as lezer-clojure.

**Comment by mk** [comment]
Should have closed this when we released https://www.npmjs.com/package/lezer-clojure a year ago…
